message

diff --git a/.github/workflows/main_process_data.yml b/.github/workflows/main_process_data.yml
--- a/.github/workflows/main_process_data.yml
+++ b/.github/workflows/main_process_data.yml
@@ -17,7 +17,7 @@ jobs:
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
-      
+
       - name: Install jq
         run: |
           apt-get update
@@ -68,49 +68,19 @@ jobs:
           echo "::set-output name=asin_subsets::$asin_subsets"
           echo "::set-output name=download_dir::$download_dir"
 
-  process-asins:
-    needs: process-keywords
-    runs-on: ubuntu-latest
-    container: utydata02/ai-listing-uty:latest
-    strategy:
-      matrix:
-        asin: ${{ fromJson(needs.process-keywords.outputs.asin_subsets) }}
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v2
-
-      - name: Set up VPN configuration
-        run: |
-          echo "${{ secrets.VPN_CONFIG }}" | base64 --decode > vpn-config.ovpn
-          echo -e "${{ secrets.VPN_USERNAME }}\n${{ secrets.VPN_PASSWORD }}" > vpn-auth.txt
-
-      - name: Connect to VPN
-        run: |
-          openvpn --config vpn-config.ovpn --auth-user-pass vpn-auth.txt --daemon
-          sleep 5  # Wait for the VPN to establish
-
-      - name: Verify VPN connection
-        run: curl ifconfig.me
-
-      - name: Process Asins with Retry
-        id: process_asin_retry
-        env:
-          DRIVER: ${{ needs.process-keywords.outputs.driver }}
-          RESULT: ${{ needs.process-keywords.outputs.result }}
-          ASIN_SUBSETS: ${{ needs.process-keywords.outputs.asin_subsets }}
-          DOWNLOAD_DIR: ${{ needs.process-keywords.outputs.download_dir }}
-        run: |
-          RETRIES=3
           for i in $(seq 1 $RETRIES); do
-            echo "Attempt $i"
-            output=$(timeout 180s python asin_main_process_data.py "${{ env.DRIVER }}" "${{ env.RESULT }}" "${{ env.ASIN_SUBSETS }}" "${{ env.DOWNLOAD_DIR }}")
-            if [ $? -eq 0 ]; then
+            echo "Attempt $i for ASINs"
+            output=$(timeout 180s python asin_main_process_data.py "$(echo $output | jq -c '.driver')" "$(echo $output | jq -c '.result')" "$(echo $output | jq -c '.asin_subsets')" "$(echo $output | jq -c '.download_dir')") || status=$?
+            if [ $status -eq 0 ]; then
+              echo "Attempt $i for ASINs succeeded."
               break
+            elif [ $status -eq 124 ]; then  # 124 is the exit code for timeout
+              echo "Attempt $i for ASINs failed due to timeout. Retrying..."
             else
-              echo "Attempt $i failed. Retrying..."
+              echo "Attempt $i for ASINs failed with status $status. Retrying..."
             fi
             if [ $i -eq $RETRIES ]; then
-              echo "All attempts failed."
+              echo "All attempts for ASINs failed."
               exit 1
             fi
           done
